### ISSUE TITLE
Weird Random Database Appearing Upon Insert

### ISSUE THREAD

**Issue by justincpresley** [ZixuanZhong/ndn-distributed-repo#5]
![Capture](https://user-images.githubusercontent.com/31783047/116026929-465faa80-a619-11eb-8e89-1a4ad91cf164.PNG)

After inserting a file, the node that gets that file creates a weird database with its globalview.db

This may just be an issue when theres only one node in the repo.

**Comment by ZixuanZhong** [comment]
That is the behavior of `global_view_2`. the global view is stored as sqlite db.

**Comment by ZixuanZhong** [comment]
check [this line](https://github.com/ZixuanZhong/ndn-distributed-repo/blob/16435142f90e7435b7dcae40c1942ecca196849d/ndn_distributed_repo/main/main.py#L63)

**Comment by justincpresley** [comment]
On startup, all nodes generates the databases as normal under:
`~/.ndn/repo/pndrepo/session_id/global_view.db` according to the node's session id (if the repo_prefix is /pndrepo)

However when using the dumper (viewing the database) or sending an insert command it generates
`~/.ndn/repo/[bytearray(b'\x08\x07pndrepo)]/global_view.db` which indicates an error on placing the repo_prefix? unless this is intended...

**Comment by justincpresley** [comment]
Fixed this error.
